management:
  context_path: /admin
security:
  user:
    password: password

debug: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
spring:
  datasource:
    url: jdbc:mysql://192.168.0.17:3306/sprint_security
    username: sprint
    password: sprint
    data-source-class-name: com.mysql.jdbc.Driver